name: CD Workflow

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Some CD JOBS
        run: echo "some CD Jobs information..."

  deploy-prod:
    uses: ./.github/workflows/deploy-prod.yaml
    needs: [cd]
    with:
      pr_number: ${{ github.event.pull_request.number }}