name: CI Workflow (Test Logs and Trigger Deploy)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  trigger_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log input information for testing
        run: |
          echo "Testing CI Workflow"
          echo "PR Number: ${{ github.event.pull_request.number }}"
          echo "Branch Name: ${{ github.event.pull_request.head.ref }}"
          echo "PR State: ${{ github.event.pull_request.state }}"
          echo "Logging some information..."

      - name: Trigger Deploy Pull Request Workflow
        uses: peter-evans/workflow-dispatch@v1
        with:
          workflow: 'deploy-pr.yml'  # The name of the workflow you want to trigger
          ref: 'refs/heads/main'  # The branch to trigger the workflow on
          inputs: | 
            pr_number: ${{ github.event.pull_request.number }}
            branch_name: ${{ github.event.pull_request.head.ref }}
            pr_state: ${{ github.event.pull_request.state }}
