name: CI Workflow

on:
  pull_request:
    types: [opened, synchronize]

concurrency:
  group: ${{ github.event.pull_request.number }}
  cancel-in-progress: true


jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log input information for testing
        run: |
          echo "PR Number: ${{ github.event.pull_request.number }}"
          echo "Branch Name: ${{ github.event.pull_request.head.ref }}"
          echo "PR State: ${{ github.event.pull_request.state }}"
          echo "Logging some information..."

  deploy-pr:
    uses: ./.github/workflows/deploy-pr.yaml
    needs: [ci]
    with:
      pr_number: 1234  # Hardcoded PR number
      branch_name: feature/test-branch  # Hardcoded branch name
      pr_state: open  # Hardcoded PR state
