name: CI Workflow

on:
  pull_request:
    types: [opened, synchronize]

concurrency:
  group: ${{ github.event.pull_request.number }}
  cancel-in-progress: true


jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Some CI JOBS
        run: echo "some CI Jobs information..."

  deploy-pr:
    uses: ./.github/workflows/deploy-pr.yaml
    needs: [ci]
    with:
      pr_number: ${{ github.event.pull_request.number }}
      branch_name: ${{ github.event.pull_request.head.ref }}
      pr_state: ${{ github.event.pull_request.action }}
