name: Clean Up PR Environment

on:
  pull_request:
    types: [closed]  

jobs:
  clean-up-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get PR Number and Branch Name
        id: env
        run: |
          echo "PR Number: ${{ github.event.pull_request.number }}"
          echo "Branch Name: ${{ github.event.pull_request.head.ref }}"
          echo "pr_number=${{ github.event.pull_request.number }}" >> $GITHUB_ENV
          echo "branch_name=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV

      - name: Generate Environment Name
        run: |
          ENV_NAME="pr-${{ env.pr_number }}"
          echo "The environment name for cleanup is: $ENV_NAME"
          echo "env_name=$ENV_NAME" >> $GITHUB_ENV

      - name: Log Clean Up Environment
        run: |
          echo "Cleaning up environment for PR #${{ env.pr_number }} on branch ${{ env.branch_name }}"
          echo "Environment cleanup complete for pr-${{ env.pr_number }} atulsingh.dev"
