name: Deploy to Prod

on:
  workflow_call:
    inputs:
      pr_number:
        description: 'Pull Request Number'
        required: true
        type: number

jobs:
  deploy-prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment name # for cleaning up pr environment
        id: env
        run: echo "env_name=pr-${{inputs.pr_number}}" >> $GITHUB_ENV

      - name: Delete Pr environment
        run: |
          echo "Deleted : ${{ env.env_name }}.atulsingh.dev"
          
      - name: Get Artifact Version
        id: artifact
        run: |
          echo "artifact_version=${"version"  .odin/static-pages-remix/application-spec.yml | awk -F ": " '{print $2}' | grep -o '^[0-9]\+\.[0-9]\+\.[0-9]\+' |  awk -F. '{print $1"."$2"."$3-1}'}" >> $GITHUB_ENV

      - name: Deploy to Environment
        run: |
          echo "Deploying to environment: www.atulsingh.dev $artifact_version"
