name: Deploy Pull Request

on:
  workflow_call:
    inputs:
      pr_number:
        description: 'Pull Request Number'
        required: true
        type: number
      branch_name:
        description: 'Source Branch Name'
        required: true
        type: string
      pr_state:
          description: 'Pull Request State (e.g., open, closed)'
          required: true
          type: string


jobs:
  deploy-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment name
        id: env
        run: echo "env_name=pr-${{inputs.pr_number}}" >> $GITHUB_ENV
      
      - name: Create Environment
        id: create-env
        if: ${{ inputs.pr_state == 'opened' }}
        run: echo "creating environment ${{inputs.pr_state}}"

      - name: Deploy to Environment
        run: |
          echo "Deploying to environment:${{inputs.pr_state}} ${{ env.env_name }}.atulsingh.dev"

      - name: Generate Deployment URL
        id: set-url
        run: echo "::set-output name=url::https://example.com/${{ env.env_name }}"
  
      - name: Create commit comment
        uses: peter-evans/commit-comment@v2
        with:
          body: |
            Artifact uploaded to jfrog for service:${{ steps.set-url.outputs.url }}
              