name: Deploy to Prod

on:
  workflow_dispatch:
    inputs:
      artifact_version:
        description: "Artifact version (optional)"
        required: false
        default: ""

jobs:
  deploy-prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment name 
        id: env
        run: echo "env_name=pr-${{inputs.pr_number}}" >> $GITHUB_ENV

      - name: Delete Pr environment
        run: |
          echo "Deleted : ${{ env.env_name }}.atulsingh.dev"
          
      - name: Set Artifact Version
        id: artifact
        run: |
          if [ -z "${{ github.event.inputs.artifact_version }}" ]; then
            ARTIFACT_VERSION=$(grep  "version"  application-spec.yml | awk -F ": " '{print $2}' | grep -o '^[0-9]\+\.[0-9]\+\.[0-9]\+' |  awk -F. '{print $1"."$2"."$3-1}')
          else
            ARTIFACT_VERSION=${{ github.event.inputs.artifact_version }}
          fi
          echo "ARTIFACT_VERSION=$ARTIFACT_VERSION" >> $GITHUB_ENV

      - name: Deploy to Environment
        run: |
          echo "Deploying to environment: www.atulsingh.dev  ${{ env.ARTIFACT_VERSION }} ${{ github.actor }}"
