name: Deploy Pull Request

on:
  workflow_call:
    inputs:
      pr_number:
        description: 'Pull Request Number'
        required: true
        type: number
      branch_name:
        description: 'Source Branch Name'
        required: true
        type: string
      pr_state:
        description: 'State of the PR (open or closed)'
        required: true
        type: string

jobs:
  deploy-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Debug Inputs (Print passed inputs)
        run: |
          echo "Received PR Number: ${{inputs.pr_number }}"
          echo "Received Branch Name: ${{inputs.branch_name }}"
          echo "Received PR State: ${{inputs.pr_state }}"

      - name: Set up environment name
        id: env
        run: |
          PR_NUMBER="${{inputs.pr_number }}"
          BRANCH_NAME="${{inputs.branch_name }}"
          ENV_NAME="pr-${PR_NUMBER}-${BRANCH_NAME}"
          echo "The unique environment name is: $ENV_NAME"
          echo "env_name=$ENV_NAME" >> $GITHUB_ENV  # Set the env_name output as an environment variable

      - name: Log Deploy to Environment
        run: |
          echo "Deploying to environment: ${{ env.env_name }}"

      - name: Log Clean up Environment (if PR is closed)
        if: ${{inputs.pr_state == 'closed' }}
        run: |
          echo "Cleaning up environment: ${{ env.env_name }}"
          # Simulate environment cleanup (without actual delete command)
          echo "Environment cleanup complete for ${{ env.env_name }}"
