name: Deploy to Prod

on:
  workflow_call:
    inputs:
      pr_number:
        description: 'Pull Request Number'
        required: true
        type: number

jobs:
  deploy-prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment name # for cleaning up pr environment
        id: env
        run: echo "env_name=pr-${{inputs.pr_number}}" >> $GITHUB_ENV

      - name: Delete Pr environment
        run: |
          echo "Deleted : ${{ env.env_name }}.atulsingh.dev"

      - name: Deploy to Environment
        run: |
          echo "Deploying to environment: ${{ env.env_name }}.atulsingh.dev"
