name: Deploy Pull Request

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log Deploy to Environment
        run: |
          echo "Deploying to environment:"
