name: Deploy Pull Request

on:
  workflow_call:
    inputs:
      pr_number:
        description: 'Pull Request Number'
        required: true
        type: number
      branch_name:
        description: 'Source Branch Name'
        required: true
        type: string
      pr_state:
          description: 'Pull Request State (e.g., open, closed)'
          required: true
          type: string


jobs:
  deploy-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment name
        id: env
        run: echo "env_name=sp-${{inputs.pr_number}}" >> $GITHUB_ENV
      
      - name: Create Environment
        id: create-env
        if: ${{ inputs.pr_state == 'opened' }}
        run: echo "creating environment ${{inputs.pr_state}}"

      - name: Deploy to Environment
        run: |
          echo "Deploying to environment:${{inputs.pr_state}} ${{ env.env_name }}.atulsingh.dev"
  
      - uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `The testing environment is live! You can [view it here](https://${{env.env_name}}.example.com/)`
            })

      - name: Read the single file in the folder
        run: |
              FOLDER_PATH="src/routes"
      
              # Find the single file in the folder
              FILE=$(ls "$FOLDER_PATH" | head -n 1)
      
              # Check if a file is found
              if [ -z "$FILE" ]; then
                echo "No file found in the folder."
              else
                echo "Reading file: $FILE"
                cat "$FOLDER_PATH/$FILE"
              fi
              