name: Deploy Pull Request

on:
  workflow_run:
    workflows: ["CI Workflow (Test Logs and Trigger Deploy)"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment name
        id: env
        run: |
          PR_NUMBER="${{ github.event.workflow_run.head_commit.message }}"
          BRANCH_NAME="${{ github.event.workflow_run.head_commit.author.name }}"
          ENV_NAME="pr-${PR_NUMBER}-${BRANCH_NAME}"
          echo "The unique environment name is: $ENV_NAME"
          echo "::set-output name=env_name::$ENV_NAME"

      - name: Log Deploy to Environment
        run: |
          echo "Deploying to environment: ${{ steps.env.outputs.env_name }}"

      - name: Log Clean up Environment (if PR is closed)
        if: ${{ github.event.inputs.pr_state == 'closed' }}
        run: |
          echo "Cleaning up environment: ${{ steps.env.outputs.env_name }}"
          # Simulate environment cleanup (without actual delete command)
          echo "Environment cleanup complete for ${{ steps.env.outputs.env_name }}"
