name: Deploy to Prod
on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'Pull Request Number'
        required: true
        type: number

jobs:
  deploy-prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment name 
        id: env
        run: echo "env_name=pr-${{inputs.pr_number}}" >> $GITHUB_ENV

      - name: Delete Pr environment
        run: |
          echo "Deleted : ${{ env.env_name }}.atulsingh.dev"
          
      - name: Get Artifact Version
        id: artifact
        run: |
          ARTIFACT_VERSION=$(grep  "version"  application-spec.yml | awk -F ": " '{print $2}' | grep -o '^[0-9]\+\.[0-9]\+\.[0-9]\+' |  awk -F. '{print $1"."$2"."$3-1}')
          echo "artifact_version=$ARTIFACT_VERSION" >> $GITHUB_ENV

      - name: Deploy to Environment
        run: |
          echo "Deploying to environment: www.atulsingh.dev  ${{ env.artifact_version }}"
