name: Deploy Pull Request

on:
  workflow_call:
    inputs:
      pr_number:
        description: 'Pull Request Number'
        required: true
        type: number
      branch_name:
        description: 'Source Branch Name'
        required: true
        type: string

jobs:
  deploy-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment name
        id: env
        run: |
          PR_NUMBER="${{inputs.pr_number }}"
          BRANCH_NAME="${{inputs.branch_name }}"
          ENV_NAME="pr-${PR_NUMBER}"
          echo "The unique environment name is: $ENV_NAME"
          echo "env_name=$ENV_NAME" >> $GITHUB_ENV

      - name: Log Deploy to Environment
        run: |
          echo "Deploying to environment: ${{ env.env_name }}.atulsingh.dev"

      - name: Log Clean up Environment (if PR is closed)
        if: github.event_name == 'pull_request' && github.event.action == 'closed'
        run: |
          echo "deleting environment: ${{ env.env_name }}"
          echo "Environment deleting complete for ${{ env.env_name }}"
